modLoader = "javafml"
loaderVersion = "[32,)"
issueTrackerURL = "https://github.com/team-abnormals/caverns_and_chasms/issues"
license = "https://github.com/team-abnormals/caverns_and_chasms/blob/main/LICENSE.txt"

[[mods]]
    modId = "caverns_and_chasms"
    version = "${file.jarVersion}"
    logoFile = "logo.png"
    itemIcon = "caverns_and_chasms:silver_ore"
    configBackground = "caverns_and_chasms:textures/block/cobblestone_tiles.png"
    authors = "Team Abnormals"
    credits = "bageldotjpg, five, Markus1002, Rye"
    displayURL = "https://www.teamabnormals.com/mods/caverns-and-chasms"
    displayName = "Caverns & Chasms"
    description = '''
    Expands caves, mining, and more with tons of new content!
    '''

[[dependencies.caverns_and_chasms]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.19.2,1.19.3)"
    ordering = "AFTER"
    side = "BOTH"

[[dependencies.caverns_and_chasms]]
    modId = "forge"
    mandatory = true
    versionRange = "[43.2.0,)"
    ordering = "AFTER"
    side = "BOTH"

[[dependencies.caverns_and_chasms]]
    modId = "blueprint"
    mandatory = true
    versionRange = "[6.1.2,)"
    ordering = "AFTER"
    side = "BOTH"