modLoader = "javafml"
loaderVersion = "[32,)"
license = "All Rights Reserved"

[[mods]]
modId = "cave_upgrade"
version = "${file.jarVersion}"
displayName = "Cave Upgrade"
authors = "bageldotjpg, Farcr, Echolite, five, Cameron, and Jackson"
description = '''Cave Update mod'''

[[dependencies.cave_upgrade]]
  modId = "forge"
  mandatory = true
  versionRange = "[32.0.72,)"
  ordering = "AFTER"
  side = "BOTH"

[[dependencies.cave_upgrade]]
  modId = "minecraft"
  mandatory = true
  versionRange = "[1.16.1]"
  ordering = "NONE"
  side = "BOTH"
  
[[dependencies.cave_upgrade]]
  modId="abnormals_core"
  mandatory=true
  versionRange="[2.0.8,)"
  ordering="AFTER"
  side="BOTH"