modLoader = "javafml"
loaderVersion = "[32,)"
issueTrackerURL = "https://github.com/team-abnormals/caverns_and_chasms/issues"
license = "https://github.com/team-abnormals/caverns_and_chasms/blob/main/LICENSE.txt"

[[mods]]
    modId = "caverns_and_chasms"
    version = "${file.jarVersion}"
    logoFile = "logo.png"
    itemIcon = "caverns_and_chasms:silver_ore"
    configBackground = "caverns_and_chasms:textures/block/cobblestone_tiles.png"
    authors = "Team Abnormals"
    credits = "bageldotjpg, Farcr, Echolite, five, Cameron, Jackson"
    displayURL = "https://www.teamabnormals.com/mods/caverns-and-chasms"
    displayName = "Caverns & Chasms"
    description = '''
    Expands caves, mining, and more with tons of new content!
    '''

[[dependencies.caverns_and_chasms]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.18.2,1.19)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.caverns_and_chasms]]
    modId = "forge"
    mandatory = true
    versionRange = "[40.0.18,)"
    ordering = "AFTER"
    side = "BOTH"

[[dependencies.caverns_and_chasms]]
    modId = "blueprint"
    mandatory = true
    versionRange = "[5.3.0,)"
    ordering = "AFTER"
    side = "BOTH"