modLoader = "javafml"
loaderVersion = "[32,)"
issueTrackerURL = "https://github.com/team-abnormals/nether-caverns_and_chasms/issues"
license = "https://github.com/team-abnormals/nether-caverns_and_chasms/blob/main/LICENSE.txt"

[[mods]]
    modId = "caverns_and_chasms"
    version = "${file.jarVersion}"
    logoFile = "logo.png"
    authors = "Team Abnormals"
    credits = "bageldotjpg, Farcr, Echolite, five, Cameron, and Jackson"
    displayName = "Caverns & Chasms"
    description = '''
    Cave Update mod
    '''

[[dependencies.caverns_and_chasms]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.16.3,1.17)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.caverns_and_chasms]]
    modId = "forge"
    mandatory = true
    versionRange = "[34.1.42,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.caverns_and_chasms]]
    modId = "abnormals_core"
    mandatory = true
    versionRange = "[3.0.4,)"
    ordering = "AFTER"
    side = "BOTH"